### ISSUE TITLE
Plexamp question

### ISSUE THREAD

**Issue by matemoln** [snorre-k/musicbox#6]
Hi,
Do you have [this issue](https://forums.plex.tv/t/plexamp-rpi-soundcard-exclusive-control/378884) solved in your Plexamp installation?
Thanks for the scripts!

**Comment by snorre-k** [comment]
The issue is resolved in general, as an ALSA software mixer is setup in [asound.conf](https://github.com/snorre-k/musicbox/blob/master/scripts/hifiberry/asound.conf) in the HifiBerry [setup](https://github.com/snorre-k/musicbox/tree/master/scripts/hifiberry). The solution is taken from [here](https://support.hifiberry.com/hc/en-us/articles/207397665-Mixing-different-audio-sources).

**Comment by matemoln** [comment]
Just got around to do this. Thank you very much! 👍
